# Google Cloud Build configuration
steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - -t
      - gcr.io/$PROJECT_ID/feature-store:$COMMIT_SHA
      - -t
      - gcr.io/$PROJECT_ID/feature-store:latest
      - -f
      - deployment/gcp/Dockerfile.gcp
      - .

  # Step 2: Push Docker image (commit sha)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - gcr.io/$PROJECT_ID/feature-store:$COMMIT_SHA

  # Step 3: Push Docker image (latest)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - gcr.io/$PROJECT_ID/feature-store:latest

  # Step 4: Run tests
  - name: 'gcr.io/$PROJECT_ID/feature-store:$COMMIT_SHA'
    entrypoint: 'sh'
    args:
      - -c
      - |
        pip install pytest pytest-asyncio
        pytest tests/unit/ -v
    env:
      - 'ENV=test'

  # Step 5: Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - run
      - deploy
      - feature-store
      - --image=gcr.io/$PROJECT_ID/feature-store:$COMMIT_SHA
      - --region=us-central1
      - --platform=managed
      - --allow-unauthenticated
      - --memory=2Gi
      - --cpu=2
      - --min-instances=2
      - --max-instances=50
      - --port=8000
      - --set-env-vars=ENV=gcp
      - --set-env-vars=GCP_PROJECT_ID=$PROJECT_ID

images:
  - 'gcr.io/$PROJECT_ID/feature-store:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/feature-store:latest'

options:
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: 100

timeout: '1200s'  # 20 minutes

substitutions:
  _REGION: 'us-central1'
  _SERVICE_NAME: 'feature-store'