# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc


import feature_store_pb2 as feature__store__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in feature_store_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FeatureStoreStub(object):
    """Service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetUserFeatures = channel.unary_unary(
                '/feature_store.FeatureStore/GetUserFeatures',
                request_serializer=feature__store__pb2.UserFeatureRequest.SerializeToString,
                response_deserializer=feature__store__pb2.UserFeatureResponse.FromString,
                _registered_method=True)
        self.GetBatchFeatures = channel.unary_unary(
                '/feature_store.FeatureStore/GetBatchFeatures',
                request_serializer=feature__store__pb2.BatchFeatureRequest.SerializeToString,
                response_deserializer=feature__store__pb2.BatchFeatureResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/feature_store.FeatureStore/HealthCheck',
                request_serializer=feature__store__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=feature__store__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class FeatureStoreServicer(object):
    """Service definition
    """

    def GetUserFeatures(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBatchFeatures(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FeatureStoreServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetUserFeatures': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserFeatures,
                    request_deserializer=feature__store__pb2.UserFeatureRequest.FromString,
                    response_serializer=feature__store__pb2.UserFeatureResponse.SerializeToString,
            ),
            'GetBatchFeatures': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBatchFeatures,
                    request_deserializer=feature__store__pb2.BatchFeatureRequest.FromString,
                    response_serializer=feature__store__pb2.BatchFeatureResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=feature__store__pb2.HealthCheckRequest.FromString,
                    response_serializer=feature__store__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'feature_store.FeatureStore', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('feature_store.FeatureStore', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FeatureStore(object):
    """Service definition
    """

    @staticmethod
    def GetUserFeatures(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/feature_store.FeatureStore/GetUserFeatures',
            feature__store__pb2.UserFeatureRequest.SerializeToString,
            feature__store__pb2.UserFeatureResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBatchFeatures(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/feature_store.FeatureStore/GetBatchFeatures',
            feature__store__pb2.BatchFeatureRequest.SerializeToString,
            feature__store__pb2.BatchFeatureResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/feature_store.FeatureStore/HealthCheck',
            feature__store__pb2.HealthCheckRequest.SerializeToString,
            feature__store__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
